select * from shop;

-- Q1 What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue 
from shop 
group by gender;

-- Q2 Which customer used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount 
from shop 
where discount_applied='yes' and purchase_amount>=(select avg(purchase_amount) from shop);

-- Q3 What are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as 'Average Rating'
from shop
group by item_purchased order by avg(review_rating) desc limit 5;

-- Q4 Compare average purchase amounts between standard and express shipping?
select round(avg(purchase_amount),2), shipping_type
from shop
where shipping_type in('standard', 'express') group by shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscibers and non-subscribers?
select subscription_status,count(customer_id),round(avg(purchase_amount),2) as 'Average Revenue',sum(purchase_amount) as 'Total Revenue'
from shop
group by subscription_status;

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round((sum(case when discount_applied='yes' then 1 else 0 end)/count(*))*100,2) as discount_rate
from shop
group by item_purchased
order by discount_rate desc limit 5;

-- Q7 Segment customers into new,returning and loyal based on their total no. of previous purchases, and show the count of each segment?
with customer_type as(
select previous_purchases,
case
    when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
end as customer_segment
from shop
)
select customer_segment,count(*) as 'no. of customers' from customer_type 
group by customer_segment;

-- Q8 What are the top 3 most purchased products wihin each category?
with item_counts as(
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from shop group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts where item_rank<=3;

-- Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select count(customer_id),subscription_status
from shop
where previous_purchases>5
group by subscription_status;

-- Q10 What is the revenue contribution of each age group?
select age_group,sum(purchase_amount)
from shop
group by age_group order by sum(purchase_amount) desc;


